"""Test fixtures for lithicore.

Provides synthetic meshes with known geometry for all measurement tests.
"""

import numpy as np
import pytest
import trimesh


@pytest.fixture
def rectangular_prism():
    """A 50x30x10 mm rectangular prism simulating a standardised blade."""
    box = trimesh.creation.box(extents=[50, 30, 10])
    box.vertices += [0, 0, 5]  # centre at origin
    return box


@pytest.fixture
def oriented_prism(rectangular_prism):
    """A rectangular prism with known orientation (platform = XY plane)."""
    mesh = rectangular_prism.copy()
    # Already axis-aligned: length along Z=50, width along X=30, thickness along Y=10
    return mesh


@pytest.fixture
def synthetic_flake():
    """A simple flake-shaped mesh with a flat platform region.

    Generated by cutting a box with a slanted plane to create
    a dorsal surface at ~70deg from the platform plane.
    """
    box = trimesh.creation.box(extents=[40, 20, 15])
    # Add a slanted cut to simulate dorsal surface
    plane_normal = [0, 0.342, 0.940]  # ~70deg from platform
    plane_origin = [0, 0, 5]
    # Slice the box and keep the portion below the plane
    sliced = trimesh.intersections.slice_mesh_plane(
        box, plane_normal, plane_origin, cap=True
    )
    return sliced


@pytest.fixture
def sample_ply_path(tmp_path):
    """A sample PLY file on disk for batch processing tests."""
    mesh = trimesh.creation.box(extents=[10, 10, 10])
    path = tmp_path / "test_cube.ply"
    mesh.export(path)
    return path


@pytest.fixture
def mesh_dir_with_various(tmp_path):
    """Directory with PLY, OBJ, and STL test files for batch tests."""
    for name, ext in [("cube", "ply"), ("sphere", "obj"), ("cone", "stl")]:
        if name == "cube":
            m = trimesh.creation.box(extents=[10, 10, 10])
        elif name == "sphere":
            m = trimesh.creation.icosphere()
        else:
            m = trimesh.creation.cone(radius=5, height=10)
        m.export(tmp_path / f"{name}.{ext}")
    return tmp_path
